version: '3.7'
#
#  Component arrangement is as below:
#  
#  ┌────────────┐    ┌────────────┐   ┌─────────────┐    ┌──────────┐
#  │            │    │            │   │             │    │          │
#  │ Simulator  ├───►│ Simulator  ├──►│  SDK Scheme ├───►│  Switch  │
#  │ Backend    │    │   Core     │   │    Adapter  │    │          │
#  │   (TTK)    │◄───┤ Connector  │◄──┤             │◄───┤  (TTK)   │
#  └────────────┘    └────────────┘   └─────────────┘    └──────────┘
#  

services:

  frontend:
    image: pm4ml/mojaloop-payment-manager-ui:1.17.6
    environment:
      - API_BASE_URL=http://127.0.0.1:4010
    ports:
       - "8081:8080"
    depends_on:
      - experience-api
    profiles:
      - portal

  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://127.0.0.1:8080/auth
      - KEYCLOAK_IMPORT=/tmp/pm4ml-realm.json
      - DB_VENDOR=h2
    volumes:
      - ./keycloak-realm.json:/tmp/pm4ml-realm.json
    ports:
      - "8080:8080"
    profiles:
      - portal

  experience-api:
    image: pm4ml/mojaloop-payment-manager-experience-api:3.0.0-snapshot.11
    ports:
      - "4010:3000"
    environment:
      - APP_KEYS=myroot
      - AUTH_CLIENT_ID=pm4ml-customer-ui
      - AUTH_CLIENT_SECRET=a857e3d7-ebd4-4451-aabd-bcb480dde1a3
      - AUTH_DISCOVERY_ENDPOINT=http://keycloak:8080/auth/realms/pm4ml/.well-known/openid-configuration
      - AUTH_LOGGED_IN_LANDING_URL=http://127.0.0.1:8081/
      - AUTH_REDIRECT_NAME=pm4ml-customer-ui
      - AUTH_REDIRECT_URI=http://127.0.0.1:4010/auth
      - AUTH_RESOURCE_NAME=pm4ml-customer-ui
      - AUTH_SCOPES=roles
      - DFSP_ID=mentd-test
      - ENV_ID=1
      - MANAGEMENT_ENDPOINT=management-api:9000
      - METRICS_ENDPOINT=prometheus:9090
      - MOCK_DATA=false
      - SESSION_REDIS_URL=redis://redis/2
      - SESSION_SECURE=false
    depends_on:
      - management-api
      - keycloak
      - redis
    profiles:
      - portal

  management-api:
    image: mojalabtg/pm4ml-management-api:1.0.3
    environment:
      - AUTH_ENABLED=false
      - AUTH_PASS=pm4mltest123
      - AUTH_USER=pm4mltest
      - CACHE_HOST=redis
      - CACHE_SYNC_INTERVAL_SECONDS=10
      - CACHE_URL=redis://redis:6379
      - DFSP_CSR_KEY=a
      - DFSP_ID=mentd-test
      - ENV_ID=1
      - MCM_API_TOKEN=myroot
      - MCM_CLIENT_REFRESH_INTERVAL=180000
      - MCM_CLIENT_SECRETS_LOCATION=/secrets
      - MCM_SERVER_ENDPOINT=https://192.168.5.178:3001/api
      - P12_PASS_PHRASE=SOME_S3C4R3_P@SS
      - PK_SECRETS_LOCATION=/secrets
      - PRIVATE_KEY_ALGORITHM=rsa
      - PRIVATE_KEY_LENGTH=4096
      # - TLS_SERVER_PRIVATE_KEY=a
      - WS_PORT=4003
      - WS_URL=sdk-scheme-adapter
      - dfspCsrPrivateKeyAlgorithm=rsa
      - dfspCsrPrivateKeyLength=4096co
      - p12PassPhrase=SOME_S3C4R3_P@SS
      # - caCSRParametersPath=/resources/caCSRParameters.json
      # - tlsClientCSRParametersPath=/resources/tlsClientCSRParameters.json
      # - tlsServerCAPath=/tlsServerCA.pem
      - WHITELIST_IP=127.0.0.1
      - CA_CSR_PARAMETERS=/resources/caCSRParameters.json
      - DFSP_CLIENT_CSR_PARAMETERS=/resources/tlsClientCSRParameters.json
      - DFSP_SERVER_CSR_PARAMETERS=/resources/tlsServerCSRParameters.json
      - MOJALOOP_CONNECTOR_FQDN=connector.mentd-test.tg
      - VAULT_ENDPOINT=http://192.168.5.178:8200
      - HUB_IAM_PROVIDER_URL=http://127.0.0.1:80
      - VAULT_PKI_BASE_DOMAIN=mentd-test.tg
      - CALLBACK_URL=http://connector.mentd-test.tg:443
      - VAULT_AUTH_METHOD=APP_ROLE
      - VAULT_ROLE_ID_FILE=/vault/role-id
      - VAULT_ROLE_SECRET_ID_FILE=/vault/secret-id
      - VAULT_PKI_SERVER_ROLE=127.0.0.1
      - VAULT_PKI_CLIENT_ROLE=127.0.0.1
      - VAULT_MOUNT_PKI=pki
      - VAULT_MOUNT_KV=secrets
      - CERT_MANAGER_ENABLED=false

    volumes:
      # - "/tmp/secrets:/secrets"
      - ./resources:/resources
      - ./vault/tmp:/vault
      - ./secrets/tlsServerPvtKey.key:/tlsServerPvtKey.key
      - ./secrets/tlsServerCA.pem:/tlsServerCA.pem
    depends_on:
      redis:
        condition: service_started
      keycloak:
        condition: service_started
      # vault-mpm:
      #   condition: service_healthy
    profiles:
      - portal

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    profiles:
      - portal

  sim-backend:
    image: mojaloop/ml-testing-toolkit:v15.7.0
    volumes:
      - "../testing-toolkit/docker-compose/as-a-backend/spec_files:/opt/app/spec_files"
    ports:
      - "5051:5050"
    command:
      - sh
      - -c
      - "npm start"
  # NOTE: The following UI for sim backend can be enabled for debugging purpose
  sim-backend-ui:
    image: mojaloop/ml-testing-toolkit-ui:v15.1.3
    ports:
      - "6061:6060"
    environment:
      - API_BASE_URL=http://127.0.0.1:5051
      - AUTH_ENABLED=FALSE
    command:
      - sh
      - /usr/share/nginx/start.sh

  redis:
    image: redis:6.2.4-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
      - REDIS_REPLICATION_MODE=master
      - REDIS_TLS_ENABLED=no
    # ports:
    #   - "6379:6379"

  sdk-scheme-adapter:
    image: mojaloop/sdk-scheme-adapter:v23.6.0-snapshot.2
    command:
    - sh
    - -c
    - "yarn start:api-svc"
    environment:
      - AUTO_ACCEPT_PARTY=true
      - AUTO_ACCEPT_QUOTES=true
      - AUTO_ACCEPT_R2P_PARTY=false
      - BACKEND_ENDPOINT=sim-backend:4040
      - CACHE_HOST=redis
      - CACHE_PORT=6379
      - CACHE_URL=redis://redis:6379
      - DFSP_ID=mentd-test
      - ENABLE_TEST_FEATURES=true
      - INBOUND_LISTEN_PORT=4000
      - INBOUND_MUTUAL_TLS_ENABLED=false
      - IN_CA_CERT_PATH=/secrets/inbound-cacert.pem
      - IN_SERVER_CERT_PATH=/secrets/inbound-cert.pem
      - IN_SERVER_KEY_PATH=/secrets/inbound-key.pem
      - JWS_SIGN=false
      - JWS_SIGNING_KEY_PATH=/jwsSigningKey.key
      - JWS_VERIFICATION_KEYS_DIRECTORY=/jwsVerificationKeys
      - METRICS_SERVER_LISTEN_PORT=4004
      - MULTIPLE_PARTIES_RESPONSE=false
      - MGMT_API_WS_URL=management-api
      - MGMT_API_WS_PORT=4005
      - OUTBOUND_LISTEN_PORT=4001
      - OUTBOUND_MUTUAL_TLS_ENABLED=false
      - OUT_CA_CERT_PATH=/secrets/outbound-cacert.pem
      - OUT_CLIENT_CERT_PATH=/secrets/outbound-cert.pem
      - OUT_CLIENT_KEY_PATH=/secrets/outbound-key.pem
      - PEER_ENDPOINT=mojaloop-testing-toolkit:4040
      #- ALS_ENDPOINT=mojaloop-testing-toolkit:4040
      - ALS_ENDPOINT=account-lookup-localhost
      - QUOTES_ENDPOINT=quoting-localhost
      - TRANSACTION_REQUESTS_ENDPOINT=transaction-requests-localhost
      - TRANSFERS_ENDPOINT=transfers-localhost
      - BULK_QUOTES_ENDPOINT=quoting-localhost
      - BULK_TRANSFERS_ENDPOINT=bulk-transfers-localhost
      #- FX_QUOTES_ENDPOINT=mojaloop-testing-toolkit:4040
      #- FX_TRANSFERS_ENPOINT=mojaloop-testing-toolkit:4040
      - FX_QUOTES_ENDPOINT=quoting-localhost
      - FX_TRANSFERS_ENPOINT=transfers-localhost
      - TEST_CA_CERT_PATH=/secrets/test-cacert.pem
      - TEST_CLIENT_CERT_PATH=/secrets/test-cert.pem
      - TEST_CLIENT_KEY_PATH=/secrets/test-key.pem
      - TEST_LISTEN_PORT=4002
      - TEST_MUTUAL_TLS_ENABLED=false
      - WS_PORT=4003
      # - OAUTH_TOKEN_ENDPOINT={{ CHANGE BEFORE INSTALL e.g. https://extgw.dev.product.mbox-dev.io:9443/oauth2/token }}
      # - OAUTH_CLIENT_KEY={{ CHANGE BEFORE INSTALL e.g. k9edbgS09cE9qAkiVEaz5Hmuc5Ua }}
      # - OAUTH_CLIENT_SECRET={{ CHANGE BEFORE INSTALL e.g. UvMTwwj7am2agjkAfvmElNte4ewa }}
      - VALIDATE_INBOUND_JWS=false
      - RESERVE_NOTIFICATION=false
      # - RESOURCE_VERSIONS="transfers=1.1"
      - PM4ML_ENABLED=${PM4ML_ENABLED:-false}
      - ENABLE_BACKEND_EVENT_HANDLER=false
      - ENABLE_FSPIOP_EVENT_HANDLER=false
      - FSPIOP_API_SERVER_MAX_REQUEST_BYTES=209715200
      - BACKEND_API_SERVER_MAX_REQUEST_BYTES=209715200
      - SUPPORTED_CURRENCIES=TZS
      - GET_SERVICES_FXP_RESPONSE=testfxp1
    ports:
      - "4000:4000"
      - "4001:4001"
    volumes:
      - ./outbound-cacert.pem:/secrets/outbound-cacert.pem
      - ./outbound-cert.pem:/secrets/outbound-cert.pem
      - ./outbound-key.pem:/secrets/outbound-key.pem
      - ./inbound-cacert.pem:/secrets/inbound-cacert.pem
      - ./inbound-cert.pem:/secrets/inbound-cert.pem
      - ./inbound-key.pem:/secrets/inbound-key.pem
      - ./secrets/jwsSigningKey.key:/jwsSigningKey.key
      - ./secrets/jwsVerificationKeys:/jwsVerificationKeys
    restart: always
    depends_on:
      redis:
        condition: service_started
      # management-api:
      #   condition: service_started
      # management-api:
      #   condition: service_healthy

  mojaloop-testing-toolkit:
    image: mojaloop/ml-testing-toolkit:v15.7.0
    user: root
    volumes:
      - "../testing-toolkit/docker-compose/as-a-switch/spec_files:/opt/app/spec_files"
    ports:
      - "4040:4040"
      - "5050:5050"
    command:
      - sh
      - -c
      - "npm start"
  mojaloop-testing-toolkit-ui:
    image: mojaloop/ml-testing-toolkit-ui:v15.1.3
    ports:
      - "6060:6060"
    environment:
      - API_BASE_URL=http://127.0.0.1:5050
      - AUTH_ENABLED=FALSE
    command:
      - sh
      - /usr/share/nginx/start.sh

  vault-mpm:
    image: vault:1.13.3
    restart: always
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_API_ADDR: http://127.0.0.1:8200
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "8760h", "max_lease_ttl": "87600h"}'
    ports:
      - "8200:8200"
    volumes:
      - ./vault/tmp:/vault/tmp
      - ./vault/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    cap_add:
      - IPC_LOCK
    # entrypoint: ["/bin/sh", "-c", "chmod +x /vault/docker-entrypoint.sh && exec /vault/docker-entrypoint.sh"]
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/service_started"]
      timeout: 1s
      retries: 20

networks:
  default:
    driver: bridge
# networks:
#   default:
#     name: payment-manager
